version: '3'
services:
  app:
    hostname: production.ldsolutions.tk
    image: levlaz/supportservice
    environment:
      - FLASK_APP=run.py
      - DATABASE_URL=postgresql://supportService:supportService@db/supportService
      - FLASK_ENV=production
      - LD_CLIENT_KEY=5ba035689cf5aa16ab905b5f
      - LD_FRONTEND_KEY=sdk-66da9eb8-9d94-4288-9571-6097f4ad8df4
    ports:
      - "8000:8000"
    command: ./scripts/start.sh
    depends_on:
      - db
      - cache
      - apm
    
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=supportService
      - POSTGRES_PASSWORD=supportService
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cache:
    image: redis
    ports:
      - "6379:6379"
  
  web:
    image: nginx
    volumes: 
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app

  apm:
    image: elastic/apm-server:6.4.2
    volumes:
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml
    ports:
      - "8200:8200"